name: flutter_ecommerce_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.2.10+1
  image_picker: ^0.8.5+3
  firebase_core: ^1.19.2
  cloud_firestore: ^3.3.0
  firebase_auth: ^3.4.2
  animated_theme_switcher: "^1.0.9"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#ff8000" 
  color_dark: "#ffaa55"
  image: 'assets/splash_dog.png' 
  image_dark: 'assets/splash_dog.png'

flutter:
  uses-material-design: true
  assets:
   - assets/