// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxT3SJdF9xES97QmWTUrT_UAhbnwZKTbM',
    appId: '1:624118247102:android:d0136f9dcab252b543b8ef',
    messagingSenderId: '624118247102',
    projectId: 'flutterecommerceapp-a3495',
    storageBucket: 'flutterecommerceapp-a3495.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOq45tKscEhODhBM90vQCepqJ3cdBWMa0',
    appId: '1:624118247102:ios:aeca08a8b4887fe543b8ef',
    messagingSenderId: '624118247102',
    projectId: 'flutterecommerceapp-a3495',
    storageBucket: 'flutterecommerceapp-a3495.appspot.com',
    iosClientId: '624118247102-h4mus9kb25gm1guf3gu23dgo1u0ef4ml.apps.googleusercontent.com',
    iosBundleId: 'com.thealphamerc.flutterEcommerceApp',
  );
}
